### ISSUE TITLE
Cannot import platform.Context on default KottageContext() 

### ISSUE THREAD

**Issue by BergHeisen** [irgaly/kottage#137]
I'm trying to use the library to store data with Kotlin Multiplatform. Added the dependency in my shared build.gradle.kts
And when trying to add a Kottage Object to Shared code, I get 

```Cannot access class 'io.github.irgaly.kottage.platform.Context'. Check your module classpath for missing or conflicting dependencies```

The error persists on the JVM code as well, same error, is there a way to fix that? 

The code causing that bug is ```KottageContext()``` on shared/client code

**Comment by irgaly** [comment]
Thank you for your reporting to this issue!

`io.github.irgaly.kottage.platform.Context` is an internal class, so it's library's mistake that KottageContext constructor parameter needs this class.

I've fixed this issue by #138. This is released as https://github.com/irgaly/kottage/releases/tag/v1.5.1. Please try using it.

**Comment by BergHeisen** [comment]
Yes it now works, thank you very much!
